branch-defaults:
  default:
    environment: Tutorial-test
  master:
    environment: Tutorial-test-clone
global:
  application_name: tutorial
  default_ec2_keyname: aws-eb
  default_platform: php-7.2
  default_region: eu-west-1
  profile: eb-cli
  sc: null
